var Country = [
    { id: '中国 China', text: '中国 China' },
    { id: '中国 台湾 Taiwan', text: '中国 台湾 Taiwan' },
    { id: '中国 香港 Hong Kong', text: '中国 香港 Hong Kong' },
    { id: '中国澳门 Macau', text: '中国澳门 Macau' },
    { id: '英国 United Kingdom', text: '英国 United Kingdom' },
    { id: '马来西亚 Malaysia', text: '马来西亚 Malaysia' },
    { id: '新加坡 Singapore', text: '新加坡 Singapore' },
    { id: '阿尔巴尼亚 Albania', text: '阿尔巴尼亚 Albania' },
    { id: '阿尔及利亚 Algeria', text: '阿尔及利亚 Algeria' },
    { id: '安道尔 Andorra', text: '安道尔 Andorra' },
    { id: '荷属安的列斯群岛 Antilles Netherland', text: '荷属安的列斯群岛 Antilles Netherland' },
    { id: '安提瓜 Antiqua (WI)', text: '安提瓜 Antiqua (WI)' },
    { id: '阿根廷 Argentina', text: '阿根廷 Argentina' },
    { id: '亚美尼亚 Armenia', text: '亚美尼亚 Armenia' },
    { id: '阿鲁巴 Aruba', text: '阿鲁巴 Aruba' },
    { id: '澳大利亚 Australia', text: '澳大利亚 Australia' },
    { id: '奥地利 Austria', text: '奥地利 Austria' },
    { id: '阿塞拜疆 Azerbaijan', text: '阿塞拜疆 Azerbaijan' },
    { id: '巴哈马群岛 Bahamas', text: '巴哈马群岛 Bahamas' },
    { id: '巴林 Bahrain', text: '巴林 Bahrain' },
    { id: '孟加拉 Bangladesh', text: '孟加拉 Bangladesh' },
    { id: '巴巴多斯 Barbados', text: '巴巴多斯 Barbados' },
    { id: '白俄罗斯 Belarus', text: '白俄罗斯 Belarus' },
    { id: '比利时 Belgium', text: '比利时 Belgium' },
    { id: '伯利兹 Belize', text: '伯利兹 Belize' },
    { id: '贝宁 Benin', text: '贝宁 Benin' },
    { id: '百慕大 Bermuda', text: '百慕大 Bermuda' },
    { id: '不丹 Bhutan', text: '不丹 Bhutan' },
    { id: '玻利维亚 Bolivia', text: '玻利维亚 Bolivia' },
    { id: '波黑 Bosnia-Herzegovina', text: '波黑 Bosnia-Herzegovina' },
    { id: '博茨瓦纳 Botswana', text: '博茨瓦纳 Botswana' },
    { id: '巴西 Brazil', text: '巴西 Brazil' },
    { id: '英属维尔京群岛 British Virgin', text: '英属维尔京群岛 British Virgin' },
    { id: '文莱达鲁萨兰国 Brunei Darussalam', text: '文莱达鲁萨兰国 Brunei Darussalam' },
    { id: '保加利亚 Bulgaria', text: '保加利亚 Bulgaria' },
    { id: '布基纳法索 Burkina Faso', text: '布基纳法索 Burkina Faso' },
    { id: '柬埔寨 Cambodia', text: '柬埔寨 Cambodia' },
    { id: '咔麦隆 Cameroon', text: '咔麦隆 Cameroon' },
    { id: '加拿大 Canada', text: '加拿大 Canada' },
    { id: '加那利群岛 Canary Islands', text: '加那利群岛 Canary Islands' },
    { id: '佛得角 Cape Verde', text: '佛得角 Cape Verde' },
    { id: '开曼群岛 Cayman Islands', text: '开曼群岛 Cayman Islands' },
    { id: '中非 Central African', text: '中非 Central African' },
    { id: '查德 Chad', text: '查德 Chad' },
    { id: '智利 Chile', text: '智利 Chile' },
    { id: '哥伦比亚 Colombia', text: '哥伦比亚 Colombia' },
    { id: '库克群岛 Cook Islands', text: '库克群岛 Cook Islands' },
    { id: '哥斯达黎加 Costa Rica', text: '哥斯达黎加 Costa Rica' },
    { id: '克罗埃西亚 Croatia', text: '克罗埃西亚 Croatia' },
    { id: '塞浦路斯 Cyprus', text: '塞浦路斯 Cyprus' },
    { id: '捷克共和国 Czech Republic', text: '捷克共和国 Czech Republic' },
    { id: '丹麦 Denmark', text: '丹麦 Denmark' },
    { id: '吉布地 Djibouti', text: '吉布地 Djibouti' },
    { id: '多米尼加岛 Dominica', text: '多米尼加岛 Dominica' },
    { id: '东帝汶 East Timor', text: '东帝汶 East Timor' },
    { id: '多米尼加共和国 Dominican Republic', text: '多米尼加共和国 Dominican Republic' },
    { id: '厄瓜多尔 Ecuador', text: '厄瓜多尔 Ecuador' },
    { id: '埃及 Egypt', text: '埃及 Egypt' },
    { id: '萨尔瓦多 El Salvador', text: ' 萨尔瓦多 El Salvador' },
    { id: '赤道几内亚共和国 Equatorial Guinea', text: '赤道几内亚共和国 Equatorial Guinea' },
    { id: '爱沙尼亚 Estonia', text: '爱沙尼亚 Estonia' },
    { id: '埃塞俄比亚 Ethiopia', text: '埃塞俄比亚 Ethiopia' },
    { id: '法罗群岛 Faroe Islands', text: '法罗群岛 Faroe Islands' },
    { id: '斐济群岛 Fiji Islands', text: '斐济群岛 Fiji Islands' },
    { id: '芬兰 Finland', text: '芬兰 Finland' },
    { id: '法国 France', text: '法国 France' },
    { id: '法属圭亚那 French Guiana', text: '法属圭亚那 French Guiana' },
    { id: '加蓬共和国 Gabon Republic', text: '加蓬共和国 Gabon Republic' },
    { id: '冈比亚 Gambia', text: '冈比亚 Gambia' },
    { id: '乔治亚 Georgia', text: '乔治亚 Georgia' },
    { id: '德国 Germany', text: '德国 Germany' },
    { id: '加纳 Ghana', text: '加纳 Ghana' },
    { id: '直布罗陀 Gibraltar', text: '直布罗陀 Gibraltar' },
    { id: '希腊 Greece', text: '希腊 Greece' },
    { id: '格陵兰 Greenland', text: '格陵兰 Greenland' },
    { id: '格瑞那达国 Grenada', text: '格瑞那达国 Grenada' },
    { id: '瓜德罗普 Guadeloupe', text: '瓜德罗普 Guadeloupe' },
    { id: '瓜地马拉 Guatemala', text: '瓜地马拉 Guatemala' },
    { id: '几内亚 Guinea', text: '几内亚 Guinea' },
    { id: '盖亚那 Guyana', text: '盖亚那 Guyana' },
    { id: '海地 Haiti', text: '海地 Haiti' },
    { id: '洪都拉斯 Honduras', text: '洪都拉斯 Honduras' },
    { id: '匈牙利 Hungary', text: '匈牙利 Hungary' },
    { id: '冰岛 Iceland', text: '冰岛 Iceland' },
    { id: '印度 India', text: '印度 India' },
    { id: '印度尼西亚 Indonesia', text: '印度尼西亚 Indonesia' },
    { id: '爱尔兰 Ireland', text: '爱尔兰 Ireland' },
    { id: '以色列 Israel', text: '以色列 Israel' },
    { id: '意大利 Italy', text: '意大利 Italy' },
    { id: '牙买加 Jamaica', text: '牙买加 Jamaica' },
    { id: '日本 Japan', text: '日本 Japan' },
    { id: '约旦 Jordan', text: '约旦 Jordan' },
    { id: '哈萨克斯坦 Kazakhstan', text: '哈萨克斯坦 Kazakhstan' },
    { id: '肯尼亚 Kenya', text: '肯尼亚 Kenya' },
    { id: '科威特 Kuwait', text: '科威特 Kuwait' },
    { id: '库尔吉斯坦 Kyrghyzstan', text: '库尔吉斯坦 Kyrghyzstan' },
    { id: '老挝 Laos', text: '老挝 Laos' },
    { id: '拉脱维亚 Latvia', text: '拉脱维亚 Latvia' },
    { id: '黎巴嫩 Lebanon', text: '黎巴嫩 Lebanon' },
    { id: '莱索托 Lesotho', text: '莱索托 Lesotho' },
    { id: '列支敦斯登 Liechtenstein', text: '列支敦斯登 Liechtenstein' },
    { id: '立陶宛 Lithuania', text: '立陶宛 Lithuania' },
    { id: '卢森堡 Luxembourg', text: '卢森堡 Luxembourg' },
    { id: '马其顿王国 Macedonia', text: '马其顿王国 Macedonia' },
    { id: '达加斯加 Madagascar', text: '马达加斯加 Madagascar' },
    { id: '马拉威 Malawi', text: '马拉威 Malawi' },
    { id: '马来西亚 Malaysia', text: '马来西亚 Malaysia' },
    { id: '马尔代夫 Maldives', text: '马尔代夫 Maldives' },
    { id: '马利共和国 Mali', text: '马利共和国 Mali' },
    { id: '马耳他 Malta', text: '马耳他 Malta' },
    { id: '马绍尔群岛 Marshall Islands', text: '马绍尔群岛 Marshall Islands' },
    { id: '马提尼克岛 Martinique', text: '马提尼克岛 Martinique' },
    { id: '茅利塔尼亚 Mauritania', text: '茅利塔尼亚 Mauritania' },
    { id: '毛里求斯 Mauritius', text: '毛里求斯 Mauritius' },
    { id: '墨西哥 Mexico', text: '墨西哥 Mexico' },
    { id: '摩尔多瓦 Moldova', text: '摩尔多瓦 Moldova' },
    { id: '摩纳哥 Monaco', text: '摩纳哥 Monaco' },
    { id: '蒙古 Mongolia', text: '蒙古 Mongolia' },
    { id: '黑山 Montenegro', text: '黑山 Montenegro' },
    { id: '蒙特塞拉特 Montserrat', text: '蒙特塞拉特 Montserrat' },
    { id: '摩洛哥 Morocco', text: '摩洛哥 Morocco' },
    { id: '莫桑比克 Mozambique', text: '莫桑比克 Mozambique' },
    { id: '纳米比亚 Namibia', text: '纳米比亚 Namibia' },
    { id: '瑙鲁 Nauru', text: '瑙鲁 Nauru' },
    { id: '尼泊尔 Nepal', text: '尼泊尔 Nepal' },
    { id: '荷兰 Netherlands', text: '荷兰 Netherlands' },
    { id: '新喀里多尼亚 New Caledonia', text: '新喀里多尼亚 New Caledonia' },
    { id: '新西兰 New Zealand', text: '新西兰 New Zealand' },
    { id: '尼加拉瓜 Nicaragua', text: '尼加拉瓜 Nicaragua' },
    { id: '尼日尔 Niger', text: '尼日尔 Niger' },
    { id: '挪威 Norway', text: '挪威 Norway' },
    { id: '阿曼 Oman', text: '阿曼 Oman' },
    { id: '巴基斯坦 Pakistan', text: '巴基斯坦 Pakistan' },
    { id: '巴拿马 Panama', text: '巴拿马 Panama' },
    { id: '巴布亚新几内亚 Papua New Guinea', text: '巴布亚新几内亚 Papua New Guinea' },
    { id: '巴拉圭 Paraguay', text: '巴拉圭 Paraguay' },
    { id: '秘鲁 Peru', text: '秘鲁 Peru' },
    { id: '菲律宾 Philippines', text: '菲律宾 Philippines' },
    { id: '波兰 Poland', text: '波兰 Poland' },
    { id: '葡萄牙 Portugal', text: '葡萄牙 Portugal' },
    { id: '卡塔尔 Qatar', text: '卡塔尔 Qatar' },
    { id: '留尼汪岛 Reunion Is.', text: '留尼汪岛 Reunion Is.' },
    { id: '罗马尼亚 Romania', text: '罗马尼亚 Romania' },
    { id: '俄国 Russia', text: '俄国 Russia' },
    { id: '卢旺达 Rwanda', text: '卢旺达 Rwanda' },
    { id: '西萨摩亚 Samoa (Western)', text: '西萨摩亚 Samoa (Western)' },
    { id: '圣马力诺共和国 San Marino', text: '圣马力诺共和国 San Marino' },
    { id: '沙特阿拉伯 Saudi Arabia', text: '沙特阿拉伯 Saudi Arabia' },
    { id: '塞内加尔 Senegal', text: '塞内加尔 Senegal' },
    { id: '塞尔维亚 Serbia', text: '塞尔维亚 Serbia' },
    { id: '塞舌尔共和国 Seychelles Republic', text: '塞舌尔共和国 Seychelles Republic' },
    { id: '塞拉利昂 Sierra Leone', text: '塞拉利昂 Sierra Leone' },
    { id: '新加坡 Singapore', text: '新加坡 Singapore' },
    { id: '斯洛伐克共和国 Slovak Republic', text: '斯洛伐克共和国 Slovak Republic' },
    { id: '斯洛文尼亚 Slovenia', text: '斯洛文尼亚 Slovenia' },
    { id: '所罗门群岛 Solomon Islands', text: '所罗门群岛 Solomon Islands' },
    { id: '南非 South Africa', text: '南非 South Africa' },
    { id: '韩国 South Korea', text: '韩国 South Korea' },
    { id: '西班牙 Spain', text: '西班牙 Spain' },
    { id: '斯里兰卡 Sri Lanka', text: '斯里兰卡 Sri Lanka' },
    { id: '圣基茨 St. Kitts', text: '圣基茨 St. Kitts' },
    { id: '圣卢西亚 St. Lucia', text: '圣卢西亚 St. Lucia' },
    { id: '圣彼得堡 St. Pierre', text: '圣彼得堡 St. Pierre' },
    { id: '圣文森特 St. Vincent', text: '圣文森特 St. Vincent' },
    { id: '苏里南 Surinam', text: '苏里南 Surinam' },
    { id: '瑞士 Swaziland', text: '瑞士 Swaziland' },
    { id: '瑞典 Sweden', text: '瑞典 Sweden' },
    { id: '瑞士 Switzerland', text: '瑞士 Switzerland' },
    { id: '塔吉克斯坦 Tadjikistan', text: '塔吉克斯坦 Tadjikistan' },
    { id: '大溪地 Tahiti', text: '大溪地 Tahiti' },
    { id: '坦桑尼亚 Tanzania', text: '坦桑尼亚 Tanzania' },
    { id: '泰国 Thailand', text: '泰国 Thailand' },
    { id: '多哥 Togo', text: '多哥 Togo' },
    { id: '汤加 Tonga', text: '汤加 Tonga' },
    { id: '千里达 Trinidad', text: '千里达 Trinidad' },
    { id: '突尼斯 Tunisia', text: '突尼斯 Tunisia' },
    { id: '土耳其 Turkey', text: '土耳其 Turkey' },
    { id: '土库曼 Turkmenistan', text: '土库曼 Turkmenistan' },
    { id: '乌干达 Uganda', text: '乌干达 Uganda' },
    { id: '乌克兰 Ukraine', text: '乌克兰 Ukraine' },
    { id: '阿拉伯联合酋长国 United Arab Emirates', text: '阿拉伯联合酋长国 United Arab Emirates' },
    { id: '英国 United Kingdom', text: '英国 United Kingdom' },
    { id: '美国 United States', text: '美国 United States' },
    { id: '乌拉圭 Uruguay', text: '乌拉圭 Uruguay' },
    { id: '乌兹别克斯坦 Uzbekistan', text: '乌兹别克斯坦 Uzbekistan' },
    { id: '瓦努阿图共和国 Vanuatu', text: '瓦努阿图共和国 Vanuatu' },
    { id: '梵蒂冈 Vatican City', text: '梵蒂冈 Vatican City' },
    { id: '委内瑞拉 Venezuela', text: '委内瑞拉 Venezuela' },
    { id: '越南 Vietnam', text: '越南 Vietnam' },
    { id: '也门 Yemen', text: '也门 Yemen' },
    { id: '萨伊 Zaire', text: '萨伊 Zaire' },
    { id: '赞比亚 Zambia', text: '赞比亚 Zambia' }
];

var UserTitle = [
    //{ id: '_SELECT_TITLE', text: '请选择您的称谓' },
    { id: '女士', text: '女士' },
    { id: '先生', text: '先生' },
    { id: '小姐', text: '小姐' }
];


var Job = [
    { id: "Admin or Secretary", text: "秘书、文职" },
    { id: "Beauty or Fitness", text: "美容健身" },
    { id: "Business Professional", text: "商业人员" },
    { id: "Catering, Restaurant", text: "餐饮业" },
    { id: "Civil Servant or Govt", text: "政府机构" },
    { id: "Doctor, Nurse, Medical", text: "医生、护士、医疗" },
    { id: "Emergency Services", text: "急救医疗" },
    { id: "Engineer, Scientist, Technician", text: "工程技术、科学技术" },
    { id: "Estate Agent", text: "房地产业" },
    { id: "Forces", text: "军人" },
    { id: "Housewife, Househusband", text: "家庭主妇(夫)" },
    { id: "Journalist, Press, Broadcaster", text: "记者、传媒" },
    { id: "Manager or Director", text: "经理、主管" },
    { id: "Manual Worker", text: "手工业" },
    { id: "Retired", text: "退休" },
    { id: "Sales, Retail, Customer service", text: "销售、服务人员" },
    { id: "Security or Prison Worker", text: "保安" },
    { id: "Self-Employed", text: "自主经营" },
    { id: "Shop Keeper or Owner", text: "店主、业主" },
    { id: "Skilled Trade", text: "职业交易者" },
    { id: "Student", text: "学生" },
    { id: "Teaching or Academic", text: "教师、学者" },
    { id: "Unemployed", text: "无工作" },
     { id: "Else", text: "其他" }
];

var Money = [
    //{ id: "_SELECT_MONEY", text: "请选择" },
    { id: "少于 $10,000", text: "少于 $10,000" },
    { id: "$10,000 - $24,999", text: "$10,000 - $24,999" },
    { id: "$25,000 - $49,999", text: "$25,000 - $49,999" },
    { id: "$50,000 - $99,999", text: "$50,000 - $99,999" },
    { id: "$100,000 - $499,999", text: "$100,000 - $499,999" },
    { id: "$500,000 - $999,999", text: "$500,000 - $999,999" },
    { id: "$1,000,000以上", text: "$1,000,000以上" }

];



var Provinces = [
    { text: "广东省", id: "广东省" },
    { text: "北京市", id: "北京市" },
    { text: "上海市", id: "上海市" },
    { text: "天津市", id: "天津市" },
    { text: "河北省", id: "河北省" },
    { text: "山西省", id: "山西省" },
    { text: "河南省", id: "河南省" },
    { text: "辽宁省", id: "辽宁省" },
    { text: "吉林省", id: "吉林省" },
    { text: "黑龙江省", id: "黑龙江省" },
    { text: "内蒙古省", id: "内蒙古省" },
    { text: "江苏省", id: "江苏省" },
    { text: "山东省", id: "山东省" },
    { text: "安徽省", id: "安徽省" },
    { text: "浙江省", id: "浙江省" },
    { text: "福建省", id: "福建省" },
    { text: "湖北省", id: "湖北省" },
    { text: "湖南省", id: "湖南省" },
    { text: "广西省", id: "广西省" },
    { text: "江西省", id: "江西省" },
    { text: "四川省", id: "四川省" },
    { text: "贵州省", id: "贵州省" },
    { text: "云南省", id: "云南省" },
    { text: "西藏省", id: "西藏省" },
    { text: "陕西省", id: "陕西省" },
    { text: "甘肃省", id: "甘肃省" },
    { text: "青海省", id: "青海省" },
    { text: "新疆省", id: "新疆省" },
    { text: "重庆市", id: "重庆市" },
    { text: "海南省", id: "海南省" }
];


var Citys = [
{ text: "广州", id: "广州", pid: "广东省" },
    { text: "汕尾", id: "汕尾", pid: "广东省" },
    { text: "潮阳", id: "潮阳", pid: "广东省" },
    { text: "阳江", id: "阳江", pid: "广东省" },
    { text: "惠来", id: "惠来", pid: "广东省" },
    { text: "茂名", id: "茂名", pid: "广东省" },
    { text: "恩平", id: "恩平", pid: "广东省" },
    { text: "韶关", id: "韶关", pid: "广东省" },
    { text: "惠州", id: "惠州", pid: "广东省" },
    { text: "梅州", id: "梅州", pid: "广东省" },
    { text: "汕头", id: "汕头", pid: "广东省" },
    { text: "珠海", id: "珠海", pid: "广东省" },
    { text: "佛山", id: "佛山", pid: "广东省" },
    { text: "肇庆", id: "肇庆", pid: "广东省" },
    { text: "湛江", id: "湛江", pid: "广东省" },
    { text: "中山", id: "中山", pid: "广东省" },
    { text: "河源", id: "河源", pid: "广东省" },
    { text: "清远", id: "清远", pid: "广东省" },
    { text: "顺德", id: "顺德", pid: "广东省" },
    { text: "云浮", id: "云浮", pid: "广东省" },
    { text: "潮州", id: "潮州", pid: "广东省" },
    { text: "东莞", id: "东莞", pid: "广东省" },
    { text: "深圳", id: "深圳", pid: "广东省" },
    { text: "泰安", id: "泰安", pid: "广东省" },
    { text: "增城", id: "增城", pid: "广东省" },
    { text: "江门", id: "江门", pid: "广东省" },
    { text: "北京市", id: "北京市", pid: "北京市" },
    { text: "上海市", id: "上海市", pid: "上海市" },
    { text: "天津市", id: "天津市", pid: "天津市" },
    { text: "重庆市", id: "重庆市", pid: "重庆市" },
    { text: "邯郸", id: "邯郸", pid: "河北省" },
	{ text: "石家庄", id: "石家庄", pid: "河北省" },
	{ text: "保定", id: "保定", pid: "河北省" },
	{ text: "张家口", id: "张家口", pid: "河北省" },
	{ text: "承德", id: "承德", pid: "河北省" },
	{ text: "唐山", id: "唐山", pid: "河北省" },
	{ text: "廊坊", id: "廊坊", pid: "河北省" },
	{ text: "沧州", id: "沧州", pid: "河北省" },
	{ text: "衡水", id: "衡水", pid: "河北省" },
	{ text: "邢台", id: "邢台", pid: "河北省" },
	{ text: "秦皇岛", id: "秦皇岛", pid: "河北省" },
	{ text: "忻州", id: "忻州", pid: "河北省" },
	{ text: "太原", id: "太原", pid: "河北省" },
	{ text: "大同", id: "大同", pid: "河北省" },
	{ text: "阳泉", id: "阳泉", pid: "河北省" },
	{ text: "榆次", id: "榆次", pid: "河北省" },
	{ text: "长冶", id: "长冶", pid: "河北省" },
	{ text: "晋城", id: "晋城", pid: "河北省" },
	{ text: "临汾", id: "临汾", pid: "河北省" },
	{ text: "离石", id: "离石", pid: "河北省" },
	{ text: "运城", id: "运城", pid: "河北省" },
	{ text: "芮城", id: "芮城", pid: "河北省" },
	{ text: "绛县", id: "绛县", pid: "河北省" },
	{ text: "商丘", id: "商丘", pid: "河南省" },
	{ text: "郑州", id: "郑州", pid: "河南省" },
	{ text: "新乡", id: "新乡", pid: "河南省" },
	{ text: "许昌", id: "许昌", pid: "河南省" },
	{ text: "平顶山", id: "平顶山", pid: "河南省" },
	{ text: "信阳", id: "信阳", pid: "河南省" },
	{ text: "南阳", id: "南阳", pid: "河南省" },
	{ text: "开封", id: "开封", pid: "河南省" },
	{ text: "洛阳", id: "洛阳", pid: "河南省" },
	{ text: "鹤壁", id: "鹤壁", pid: "河南省" },
	{ text: "漯河", id: "漯河", pid: "河南省" },
	{ text: "驻马店", id: "驻马店", pid: "河南省" },
	{ text: "沈阳", id: "沈阳", pid: "辽宁省" },
	{ text: "铁岭", id: "铁岭", pid: "辽宁省" },
	{ text: "大连", id: "大连", pid: "辽宁省" },
	{ text: "鞍山", id: "鞍山", pid: "辽宁省" },
	{ text: "抚顺", id: "抚顺", pid: "辽宁省" },
	{ text: "本溪", id: "本溪", pid: "辽宁省" },
	{ text: "丹东", id: "丹东", pid: "辽宁省" },
	{ text: "锦州", id: "锦州", pid: "辽宁省" },
	{ text: "营口", id: "营口", pid: "辽宁省" },
	{ text: "阜新", id: "阜新", pid: "辽宁省" },
	{ text: "辽阳", id: "辽阳", pid: "辽宁省" },
	{ text: "长春", id: "长春", pid: "吉林省" },
	{ text: "吉林", id: "吉林", pid: "吉林省" },
	{ text: "延吉", id: "延吉", pid: "吉林省" },
	{ text: "四平", id: "四平", pid: "吉林省" },
	{ text: "通化", id: "通化", pid: "吉林省" },
	{ text: "白城", id: "白城", pid: "吉林省" },
	{ text: "阿城", id: "阿城", pid: "黑龙江省" },
	{ text: "哈尔滨", id: "哈尔滨", pid: "黑龙江省" },
	{ text: "齐齐哈尔", id: "齐齐哈尔", pid: "黑龙江省" },
	{ text: "牡丹江", id: "牡丹江", pid: "黑龙江省" },
	{ text: "绥化", id: "绥化", pid: "黑龙江省" },
	{ text: "黑河", id: "黑河", pid: "黑龙江省" },
	{ text: "漠河", id: "漠河", pid: "黑龙江省" },
	{ text: "伊春", id: "伊春", pid: "黑龙江省" },
	{ text: "大庆", id: "大庆", pid: "黑龙江省" },
	{ text: "呼和浩特", id: "呼和浩特", pid: "内蒙古省" },
	{ text: "包头", id: "包头", pid: "内蒙古省" },
	{ text: "乌海", id: "乌海", pid: "内蒙古省" },
	{ text: "集宁", id: "集宁", pid: "内蒙古省" },
	{ text: "南京", id: "南京", pid: "江苏省" },
	{ text: "无锡", id: "无锡", pid: "江苏省" },
	{ text: "镇江", id: "镇江", pid: "江苏省" },
	{ text: "苏州", id: "苏州", pid: "江苏省" },
	{ text: "南通", id: "南通", pid: "江苏省" },
	{ text: "扬州", id: "扬州", pid: "江苏省" },
	{ text: "盐城", id: "盐城", pid: "江苏省" },
	{ text: "徐州", id: "徐州", pid: "江苏省" },
	{ text: "连云港", id: "连云港", pid: "江苏省" },
	{ text: "常州", id: "常州", pid: "江苏省" },
	{ text: "昆山", id: "昆山", pid: "江苏省" },
	{ text: "荷泽", id: "荷泽", pid: "山东省" },
	{ text: "济南", id: "济南", pid: "山东省" },
	{ text: "青岛", id: "青岛", pid: "山东省" },
	{ text: "淄博", id: "淄博", pid: "山东省" },
	{ text: "德州", id: "德州", pid: "山东省" },
	{ text: "烟台", id: "烟台", pid: "山东省" },
	{ text: "潍坊", id: "潍坊", pid: "山东省" },
	{ text: "曲阜", id: "曲阜", pid: "山东省" },
	{ text: "威海", id: "威海", pid: "山东省" },
	{ text: "枣庄", id: "枣庄", pid: "山东省" },
	{ text: "凤阳", id: "凤阳", pid: "安徽省" },
	{ text: "合肥", id: "合肥", pid: "安徽省" },
	{ text: "蚌埠", id: "蚌埠", pid: "安徽省" },
	{ text: "芜湖", id: "芜湖", pid: "安徽省" },
	{ text: "淮南", id: "淮南", pid: "安徽省" },
	{ text: "马鞍山", id: "马鞍山", pid: "安徽省" },
	{ text: "黄山", id: "黄山", pid: "安徽省" },
	{ text: "江山", id: "江山", pid: "浙江省" },
	{ text: "杭州", id: "杭州", pid: "浙江省" },
	{ text: "安吉", id: "安吉", pid: "浙江省" },
	{ text: "海宁", id: "海宁", pid: "浙江省" },
	{ text: "宁波", id: "宁波", pid: "浙江省" },
	{ text: "绍兴", id: "绍兴", pid: "浙江省" },
	{ text: "临海(台州)", id: "临海(台州)", pid: "浙江省" },
	{ text: "温州", id: "温州", pid: "浙江省" },
	{ text: "丽水", id: "丽水", pid: "浙江省" },
	{ text: "金华", id: "金华", pid: "浙江省" },
	{ text: "普陀", id: "普陀", pid: "浙江省" },
	{ text: "福州", id: "福州", pid: "福建省" },
	{ text: "厦门", id: "厦门", pid: "福建省" },
	{ text: "宁德", id: "宁德", pid: "福建省" },
	{ text: "莆田", id: "莆田", pid: "福建省" },
	{ text: "晋江", id: "晋江", pid: "福建省" },
	{ text: "漳州", id: "漳州", pid: "福建省" },
	{ text: "龙岩", id: "龙岩", pid: "福建省" },
	{ text: "三明", id: "三明", pid: "福建省" },
	{ text: "武夷山", id: "武夷山", pid: "福建省" },
	{ text: "武汉", id: "武汉", pid: "湖北省" },
	{ text: "襄樊", id: "襄樊", pid: "湖北省" },
	{ text: "鄂州", id: "鄂州", pid: "湖北省" },
	{ text: "孝感", id: "孝感", pid: "湖北省" },
	{ text: "蕲春", id: "蕲春", pid: "湖北省" },
	{ text: "黄石", id: "黄石", pid: "湖北省" },
	{ text: "咸宁", id: "咸宁", pid: "湖北省" },
	{ text: "江陵", id: "江陵", pid: "湖北省" },
	{ text: "宜昌", id: "宜昌", pid: "湖北省" },
	{ text: "恩施", id: "恩施", pid: "湖北省" },
	{ text: "十堰", id: "十堰", pid: "湖北省" },
	{ text: "随州", id: "随州", pid: "湖北省" },
	{ text: "荆门", id: "荆门", pid: "湖北省" },
	{ text: "洪湖", id: "洪湖", pid: "湖北省" },
	{ text: "岳阳", id: "岳阳", pid: "湖南省" },
	{ text: "长沙", id: "长沙", pid: "湖南省" },
	{ text: "湘潭", id: "湘潭", pid: "湖南省" },
	{ text: "株洲", id: "株洲", pid: "湖南省" },
	{ text: "衡阳", id: "衡阳", pid: "湖南省" },
	{ text: "郴州", id: "郴州", pid: "湖南省" },
	{ text: "常德", id: "常德", pid: "湖南省" },
	{ text: "桃江", id: "桃江", pid: "湖南省" },
	{ text: "新化", id: "新化", pid: "湖南省" },
	{ text: "新宁", id: "新宁", pid: "湖南省" },
	{ text: "永顺", id: "永顺", pid: "湖南省" },
	{ text: "张家界", id: "张家界", pid: "湖南省" },
	{ text: "靖州", id: "靖州", pid: "湖南省" },
	{ text: "祁阳", id: "祁阳", pid: "湖南省" },
	{ text: "防城港", id: "防城港", pid: "广西省" },
	{ text: "南宁", id: "南宁", pid: "广西省" },
	{ text: "柳州", id: "柳州", pid: "广西省" },
	{ text: "桂林", id: "桂林", pid: "广西省" },
	{ text: "梧州", id: "梧州", pid: "广西省" },
	{ text: "玉林", id: "玉林", pid: "广西省" },
	{ text: "百色", id: "百色", pid: "广西省" },
	{ text: "钦州", id: "钦州", pid: "广西省" },
	{ text: "河池", id: "河池", pid: "广西省" },
	{ text: "北海", id: "北海", pid: "广西省" },
	{ text: "阳朔", id: "阳朔", pid: "广西省" },
	{ text: "鹰潭", id: "鹰潭", pid: "江西省" },
	{ text: "分宜", id: "分宜", pid: "江西省" },
	{ text: "南昌", id: "南昌", pid: "江西省" },
	{ text: "九江", id: "九江", pid: "江西省" },
	{ text: "上饶", id: "上饶", pid: "江西省" },
	{ text: "临川", id: "临川", pid: "江西省" },
	{ text: "宜春", id: "宜春", pid: "江西省" },
	{ text: "吉安", id: "吉安", pid: "江西省" },
	{ text: "赣州", id: "赣州", pid: "江西省" },
	{ text: "景德镇", id: "景德镇", pid: "江西省" },
	{ text: "萍乡", id: "萍乡", pid: "江西省" },
	{ text: "成都", id: "成都", pid: "四川省" },
	{ text: "北碚", id: "北碚", pid: "四川省" },
	{ text: "攀枝花", id: "攀枝花", pid: "四川省" },
	{ text: "自贡", id: "自贡", pid: "四川省" },
	{ text: "绵阳", id: "绵阳", pid: "四川省" },
	{ text: "南充", id: "南充", pid: "四川省" },
	{ text: "渠县", id: "渠县", pid: "四川省" },
	{ text: "遂宁", id: "遂宁", pid: "四川省" },
	{ text: "岳池", id: "岳池", pid: "四川省" },
	{ text: "通江", id: "通江", pid: "四川省" },
	{ text: "开县", id: "开县", pid: "四川省" },
	{ text: "梁平", id: "梁平", pid: "四川省" },
	{ text: "忠县", id: "忠县", pid: "四川省" },
	{ text: "云阳", id: "云阳", pid: "四川省" },
	{ text: "奉节", id: "奉节", pid: "四川省" },
	{ text: "巫山", id: "巫山", pid: "四川省" },
	{ text: "巫溪", id: "巫溪", pid: "四川省" },
	{ text: "城口", id: "城口", pid: "四川省" },
	{ text: "南川", id: "南川", pid: "四川省" },
	{ text: "丰都", id: "丰都", pid: "四川省" },
	{ text: "石柱", id: "石柱", pid: "四川省" },
	{ text: "垫江", id: "垫江", pid: "四川省" },
	{ text: "酉阳", id: "酉阳", pid: "四川省" },
	{ text: "秀山", id: "秀山", pid: "四川省" },
	{ text: "武隆", id: "武隆", pid: "四川省" },
	{ text: "彭水", id: "彭水", pid: "四川省" },
	{ text: "纳溪", id: "纳溪", pid: "四川省" },
	{ text: "长宁", id: "长宁", pid: "四川省" },
	{ text: "内江", id: "内江", pid: "四川省" },
	{ text: "峨眉", id: "峨眉", pid: "四川省" },
	{ text: "西昌", id: "西昌", pid: "四川省" },
	{ text: "荣经", id: "荣经", pid: "四川省" },
	{ text: "康定", id: "康定", pid: "四川省" },
	{ text: "马尔康", id: "马尔康", pid: "四川省" },
	{ text: "绵竹", id: "绵竹", pid: "四川省" },
	{ text: "旺苍", id: "旺苍", pid: "四川省" },
	{ text: "理县", id: "理县", pid: "四川省" },
	{ text: "汶川", id: "汶川", pid: "四川省" },
	{ text: "茂县", id: "茂县", pid: "四川省" },
	{ text: "松潘", id: "松潘", pid: "四川省" },
	{ text: "南坪", id: "南坪", pid: "四川省" },
	{ text: "小金", id: "小金", pid: "四川省" },
	{ text: "罗甸", id: "罗甸", pid: "贵州省" },
	{ text: "贵阳", id: "贵阳", pid: "贵州省" },
	{ text: "遵义", id: "遵义", pid: "贵州省" },
	{ text: "安顺", id: "安顺", pid: "贵州省" },
	{ text: "都匀", id: "都匀", pid: "贵州省" },
	{ text: "凯里", id: "凯里", pid: "贵州省" },
	{ text: "铜仁", id: "铜仁", pid: "贵州省" },
	{ text: "毕节", id: "毕节", pid: "贵州省" },
	{ text: "六盘水", id: "六盘水", pid: "贵州省" },
	{ text: "兴义", id: "兴义", pid: "贵州省" },
	{ text: "平坝", id: "平坝", pid: "贵州省" },
	{ text: "紫云", id: "紫云", pid: "贵州省" },
	{ text: "关岭", id: "关岭", pid: "贵州省" },
	{ text: "镇宁", id: "镇宁", pid: "贵州省" },
	{ text: "普定", id: "普定", pid: "贵州省" },
	{ text: "贵定", id: "贵定", pid: "贵州省" },
	{ text: "福泉", id: "福泉", pid: "贵州省" },
	{ text: "翁安", id: "翁安", pid: "贵州省" },
	{ text: "三都", id: "三都", pid: "贵州省" },
	{ text: "荔波", id: "荔波", pid: "贵州省" },
	{ text: "独山", id: "独山", pid: "贵州省" },
	{ text: "平塘", id: "平塘", pid: "贵州省" },
	{ text: "惠水", id: "惠水", pid: "贵州省" },
	{ text: "龙里", id: "龙里", pid: "贵州省" },
	{ text: "榕江", id: "榕江", pid: "贵州省" },
	{ text: "长顺", id: "长顺", pid: "贵州省" },
	{ text: "西双版纳", id: "西双版纳", pid: "云南省" },
	{ text: "德宏", id: "德宏", pid: "云南省" },
	{ text: "梁河", id: "梁河", pid: "云南省" },
	{ text: "畹町", id: "畹町", pid: "云南省" },
	{ text: "绥江", id: "绥江", pid: "云南省" },
	{ text: "昆明", id: "昆明", pid: "云南省" },
	{ text: "大理", id: "大理", pid: "云南省" },
	{ text: "个旧", id: "个旧", pid: "云南省" },
	{ text: "曲靖", id: "曲靖", pid: "云南省" },
	{ text: "保山", id: "保山", pid: "云南省" },
	{ text: "文山", id: "文山", pid: "云南省" },
	{ text: "玉溪", id: "玉溪", pid: "云南省" },
	{ text: "楚雄", id: "楚雄", pid: "云南省" },
	{ text: "思茅", id: "思茅", pid: "云南省" },
	{ text: "东川", id: "东川", pid: "云南省" },
	{ text: "元县", id: "元县", pid: "云南省" },
	{ text: "泸水", id: "泸水", pid: "云南省" },
	{ text: "中甸", id: "中甸", pid: "云南省" },
	{ text: "丽江", id: "丽江", pid: "云南省" },
	{ text: "堆龙德庆", id: "堆龙德庆", pid: "西藏省" },
	{ text: "曲水", id: "曲水", pid: "西藏省" },
	{ text: "尼木", id: "尼木", pid: "西藏省" },
	{ text: "仁布", id: "仁布", pid: "西藏省" },
	{ text: "萨嘎", id: "萨嘎", pid: "西藏省" },
	{ text: "岗巴", id: "岗巴", pid: "西藏省" },
	{ text: "萨迦", id: "萨迦", pid: "西藏省" },
	{ text: "定结", id: "定结", pid: "西藏省" },
	{ text: "定日", id: "定日", pid: "西藏省" },
	{ text: "聂拉木", id: "聂拉木", pid: "西藏省" },
	{ text: "吉隆", id: "吉隆", pid: "西藏省" },
	{ text: "仲巴", id: "仲巴", pid: "西藏省" },
	{ text: "错那", id: "错那", pid: "西藏省" },
	{ text: "昂仁", id: "昂仁", pid: "西藏省" },
	{ text: "拉孜", id: "拉孜", pid: "西藏省" },
	{ text: "谢通门", id: "谢通门", pid: "西藏省" },
	{ text: "南木林", id: "南木林", pid: "西藏省" },
	{ text: "隆子", id: "隆子", pid: "西藏省" },
	{ text: "扎囊", id: "扎囊", pid: "西藏省" },
	{ text: "墨脱", id: "墨脱", pid: "西藏省" },
	{ text: "洛扎", id: "洛扎", pid: "西藏省" },
	{ text: "浪卡子", id: "浪卡子", pid: "西藏省" },
	{ text: "贡嘎", id: "贡嘎", pid: "西藏省" },
	{ text: "类乌齐", id: "类乌齐", pid: "西藏省" },
	{ text: "江达", id: "江达", pid: "西藏省" },
	{ text: "贡觉", id: "贡觉", pid: "西藏省" },
	{ text: "芒康", id: "芒康", pid: "西藏省" },
	{ text: "左贡", id: "左贡", pid: "西藏省" },
	{ text: "八宿", id: "八宿", pid: "西藏省" },
	{ text: "洛隆", id: "洛隆", pid: "西藏省" },
	{ text: "边坝", id: "边坝", pid: "西藏省" },
	{ text: "丁青", id: "丁青", pid: "西藏省" },
	{ text: "普兰", id: "普兰", pid: "西藏省" },
	{ text: "巴青", id: "巴青", pid: "西藏省" },
	{ text: "比如", id: "比如", pid: "西藏省" },
	{ text: "嘉黎", id: "嘉黎", pid: "西藏省" },
	{ text: "聂荣", id: "聂荣", pid: "西藏省" },
	{ text: "班戈", id: "班戈", pid: "西藏省" },
	{ text: "申扎", id: "申扎", pid: "西藏省" },
	{ text: "措勤", id: "措勤", pid: "西藏省" },
	{ text: "双湖", id: "双湖", pid: "西藏省" },
	{ text: "扎达", id: "扎达", pid: "西藏省" },
	{ text: "革吉", id: "革吉", pid: "西藏省" },
	{ text: "樟木", id: "樟木", pid: "西藏省" },
	{ text: "日土", id: "日土", pid: "西藏省" },
	{ text: "改则", id: "改则", pid: "西藏省" },
	{ text: "措美", id: "措美", pid: "西藏省" },
	{ text: "索县", id: "索县", pid: "西藏省" },
	{ text: "尼玛", id: "尼玛", pid: "西藏省" },
	{ text: "盐井", id: "盐井", pid: "西藏省" },
	{ text: "拉萨", id: "拉萨", pid: "西藏省" },
	{ text: "日咯则市", id: "日咯则市", pid: "西藏省" },
	{ text: "山南", id: "山南", pid: "西藏省" },
	{ text: "林芝", id: "林芝", pid: "西藏省" },
	{ text: "昌都", id: "昌都", pid: "西藏省" },
	{ text: "那曲", id: "那曲", pid: "西藏省" },
	{ text: "阿里", id: "阿里", pid: "西藏省" },
	{ text: "西安", id: "西安", pid: "陕西省" },
	{ text: "咸阳", id: "咸阳", pid: "陕西省" },
	{ text: "延安", id: "延安", pid: "陕西省" },
	{ text: "榆林", id: "榆林", pid: "陕西省" },
	{ text: "渭南", id: "渭南", pid: "陕西省" },
	{ text: "商洛(商州)", id: "商洛(商州)", pid: "陕西省" },
	{ text: "安康", id: "安康", pid: "陕西省" },
	{ text: "城固", id: "城固", pid: "陕西省" },
	{ text: "宝鸡", id: "宝鸡", pid: "陕西省" },
	{ text: "耀县", id: "耀县", pid: "陕西省" },
	{ text: "临夏县", id: "临夏县", pid: "甘肃省" },
	{ text: "兰州", id: "兰州", pid: "甘肃省" },
	{ text: "定西", id: "定西", pid: "甘肃省" },
	{ text: "平凉", id: "平凉", pid: "甘肃省" },
	{ text: "合水", id: "合水", pid: "甘肃省" },
	{ text: "古浪", id: "古浪", pid: "甘肃省" },
	{ text: "张掖", id: "张掖", pid: "甘肃省" },
	{ text: "玉门", id: "玉门", pid: "甘肃省" },
	{ text: "张家川", id: "张家川", pid: "甘肃省" },
	{ text: "武都", id: "武都", pid: "甘肃省" },
	{ text: "甘南州", id: "甘南州", pid: "甘肃省" },
	{ text: "平川", id: "平川", pid: "甘肃省" },
	{ text: "武山", id: "武山", pid: "甘肃省" },
	{ text: "海晏", id: "海晏", pid: "青海省" },
	{ text: "西宁", id: "西宁", pid: "青海省" },
	{ text: "海东", id: "海东", pid: "青海省" },
	{ text: "同仁", id: "同仁", pid: "青海省" },
	{ text: "兴海", id: "兴海", pid: "青海省" },
	{ text: "玛沁", id: "玛沁", pid: "青海省" },
	{ text: "玉树", id: "玉树", pid: "青海省" },
	{ text: "德令哈", id: "德令哈", pid: "青海省" },
	{ text: "门源", id: "门源", pid: "青海省" },
	{ text: "格尔木市", id: "格尔木市", pid: "青海省" },
	{ text: "河南县", id: "河南县", pid: "青海省" },
	{ text: "泽库", id: "泽库", pid: "青海省" },
	{ text: "李家峡", id: "李家峡", pid: "青海省" },
	{ text: "乌兰", id: "乌兰", pid: "青海省" },
	{ text: "都兰", id: "都兰", pid: "青海省" },
	{ text: "天峻", id: "天峻", pid: "青海省" },
	{ text: "治多", id: "治多", pid: "青海省" },
	{ text: "海北", id: "海北", pid: "青海省" },
	{ text: "杂多", id: "杂多", pid: "青海省" },
	{ text: "曲麻莱", id: "曲麻莱", pid: "青海省" },
	{ text: "龙羊峡", id: "龙羊峡", pid: "青海省" },
	{ text: "茫崖", id: "茫崖", pid: "青海省" },
	{ text: "贵德", id: "贵德", pid: "青海省" },
	{ text: "贵南", id: "贵南", pid: "青海省" },
	{ text: "同德", id: "同德", pid: "青海省" },
	{ text: "祁连", id: "祁连", pid: "青海省" },
	{ text: "刚察", id: "刚察", pid: "青海省" },
	{ text: "大柴旦", id: "大柴旦", pid: "青海省" },
	{ text: "冷湖", id: "冷湖", pid: "青海省" },
	{ text: "达日", id: "达日", pid: "青海省" },
	{ text: "玛多", id: "玛多", pid: "青海省" },
	{ text: "班玛", id: "班玛", pid: "青海省" },
	{ text: "甘德", id: "甘德", pid: "青海省" },
	{ text: "久治", id: "久治", pid: "青海省" },
	{ text: "额敏", id: "额敏", pid: "新疆省" },
	{ text: "巴里坤", id: "巴里坤", pid: "新疆省" },
	{ text: "策勒", id: "策勒", pid: "新疆省" },
	{ text: "青河", id: "青河", pid: "新疆省" },
	{ text: "阿图什布", id: "阿图什布", pid: "新疆省" },
	{ text: "博乐", id: "博乐", pid: "新疆省" },
	{ text: "克拉玛依", id: "克拉玛依", pid: "新疆省" },
	{ text: "乌鲁木齐", id: "乌鲁木齐", pid: "新疆省" },
	{ text: "乌苏", id: "乌苏", pid: "新疆省" },
	{ text: "石河子", id: "石河子", pid: "新疆省" },
	{ text: "奇台", id: "奇台", pid: "新疆省" },
	{ text: "吐鲁番", id: "吐鲁番", pid: "新疆省" },
	{ text: "库尔勒", id: "库尔勒", pid: "新疆省" },
	{ text: "乌什", id: "乌什", pid: "新疆省" },
	{ text: "塔什库尔干", id: "塔什库尔干", pid: "新疆省" },
	{ text: "察布查尔", id: "察布查尔", pid: "新疆省" },
	{ text: "儋州", id: "儋州", pid: "海南省" },
	{ text: "海口", id: "海口", pid: "海南省" },
	{ text: "三亚", id: "三亚", pid: "海南省" },
	{ text: "兴隆", id: "兴隆", pid: "海南省" },

    { text: "长治", id: "长治", pid: "山西省" },
    { text: "大同", id: "大同", pid: "山西省" },
    { text: "晋城", id: "晋城", pid: "山西省" },
    { text: "晋中", id: "晋中", pid: "山西省" },
    { text: "临汾", id: "临汾", pid: "山西省" },
    { text: "吕梁", id: "吕梁", pid: "山西省" },
    { text: "朔州", id: "朔州", pid: "山西省" },
    { text: "太原", id: "太原", pid: "山西省" },
    { text: "忻州", id: "忻州", pid: "山西省" },
    { text: "阳泉", id: "阳泉", pid: "山西省" },
    { text: "运城", id: "运城", pid: "山西省" },
];

function BindSelect(dom, value)
{
    var html = "";
    for (var i = 0; i < value.length; i++) {
        html += "<option value='" + value[i].id + "'>" + value[i].text + "</option>";
    }
    $(dom).append(html);
}

//去除所有的空格
function delHtmlTag(str) {
    var strHtml = str.replace(/<\/?[^,text:"]*,text:"/gim, "");//去掉所有的html标记
    var result = strHtml.replace(/(^\s+)|(\s+$)/g, "");//去掉前后空格
    return result.replace(/\s/g, "");//去除文章中间空格
}
//验证邮箱
function CheckMail(mail) {
    var re = /^(\w-*\.*)+@(\w-?)+(\.\w{2,})+$/;
    if (!re.test(mail)) {
        //$.ligerDialog.warn("邮箱格式错误!");
        return false;
    } else {
        return true;
    }
}